### PR TITLE
New Stack operations #44: isEmpty

### PR DESCRIPTION
**Pull request by jlr52**
Hi fern4lvarez,

This pull request fixes the code reviews from https://github.com/fern4lvarez/piladb/pull/65

1. Pull request merging to dev-0.2 instead of master
2. change handler and api name to empty to conform naming convention
3. Implement Empty function in stack.go
4. Enforce 100% code test coverage.
5. Allow maintainer to edit pull request.

Description:

    Added isEmpty functionality to api. Now client can access is_empty rest call to
    determine if the stack associated to the pass in stack id and db id is empty or not.

Testing Methodology:

    Verify the following curl call will return is_empty = false

        curl -XPUT "localhost:1205/databases?name=MY_DATABASE"
        curl -XPUT "localhost:1205/databases/MY_DATABASE/stacks?name=BOOKSHELF"
        curl -XPOST localhost:1205/databases/MY_DATABASE/stacks/BOOKSHELF \
            -d '{"element":{"title":"1984","author":"George Orwell","ISBN":"1595404325","comments":[]}}'
        curl "localhost:1205/databases/MY_DATABASE/stacks/BOOKSHELF?is_empty"

    Verify the following curl call will return is_empty = true

            curl -XPUT "localhost:1205/databases?name=MY_DATABASE"
            curl -XPUT "localhost:1205/databases/MY_DATABASE/stacks?name=BOOKSHELF"
            curl "localhost:1205/databases/MY_DATABASE/stacks/BOOKSHELF?is_empty"

    Verify that empty db or stack will have standard empty response

### CODE REVIEW

**Comment by fern4lvarez** [comment]
This looks great now 👌

I added some small fixes, mostly formatting, wording and naming related. Then with a bit of time I'll try the functionality itself, update CHANGELOG and Merge :star: 

@jlr52 can you in the meantime update the `pilad` README.md file? Adding something like this, but for `EMPTY`? https://github.com/fern4lvarez/piladb/blob/master/pilad/README.md#get-databasesdatabase_idstacksstack_idsize

Thanks and great work!

**Comment by jlr52** [comment]
@fern4lvarez 

For sure, I will update it docs on my next pull request. Thanks for fixing the coding styles and mismatch %v, I will be more meticulous next time.

**Comment by fern4lvarez** [comment]
@jlr52 you can do it in this same PR.

**Comment by jlr52** [comment]
Doc is added.

**Comment by fern4lvarez** [comment]
Merged :tada:

**Pull request merged**
