### PR TITLE
New Stack operations #44: FULL

### PR DESCRIPTION
**Pull request by jlr52**
I am not really sure if putting `isMaxStackSize` in `pilad/config.go` is the best way, feel like check full should be encapsulate in the stack itself.

I am open to suggestion.

    Description:
    
        Add a new rest endpoint FULL which checks if a particular stack is full or not.
    
    Testing Methodology:
    
        Verify the following curl call to full will return full = true
    
            ./bin/pilad -max-stack-size 0
            curl -XPUT "localhost:1205/databases?name=MY_DATABASE"
            curl -XPUT "localhost:1205/databases/MY_DATABASE/stacks?name=BOOKSHELF"
            curl -XPOST localhost:1205/databases/MY_DATABASE/stacks/BOOKSHELF \
                -d '{"element":{"title":"1984","author":"George Orwell","ISBN":"1595404325","comments":[]}}'
            curl "localhost:1205/databases/MY_DATABASE/stacks/BOOKSHELF?full"
    
        Verify the following curl call to full will return full = false
    
            ./bin/pilad -max-stack-size 2
            curl -XPUT "localhost:1205/databases?name=MY_DATABASE"
            curl -XPUT "localhost:1205/databases/MY_DATABASE/stacks?name=BOOKSHELF"
            curl -XPOST localhost:1205/databases/MY_DATABASE/stacks/BOOKSHELF \
                -d '{"element":{"title":"1984","author":"George Orwell","ISBN":"1595404325","comments":[]}}'
            curl "localhost:1205/databases/MY_DATABASE/stacks/BOOKSHELF?full"

### CODE REVIEW

**Comment by fern4lvarez** [comment]
Thanks @jlr52! I was out for holidays, expect me to take a look at this in the following days.

**Comment by fern4lvarez** [comment]
> I am not really sure if putting isMaxStackSize in pilad/config.go is the best way, feel like check full should be encapsulate in the stack itself.

From my point of view, handling the size and fullness of a Stack is a responsibility of the implementation of the Pila, in this case `pilad`. What I mean is, `github.com/fern4lvarez/piladb/pila` library is size agnostic, Stacks have infinite size by default. Is the task of the user of the library to decide how to handle this. This is why all the logic of the size is part of the `github.com/fern4lvarez/piladb/config` package, and not of the Stack implementation.

So far, your approach looks good to me and I'd carry on with it.

I will shortly push some tiny changes, but in general it looks pretty good.

**Comment by fern4lvarez** [comment]
What I changed:
* I renamed `isMaxStackSize` to `isStackFull` to be more explicit and intuitive.
* Simplify implementation of `isStackFull` and re-use it in `checkMaxStackSize` Handler.
* Few manual format changes: comments, new lines, etc.
* `goimports` automatic format changes.

**Comment by jlr52** [comment]
@fern4lvarez 

Sounds good. I am ok with putting logic dictating fullness of a Stack in `pila` as it seems to be consistent with the existing code. Just wanted to double check that you are ok with it.

**Comment by fern4lvarez** [comment]
LGTM

**Pull request merged**
